package io.r2dbc.mysqlx;

import com.mysql.cj.xdevapi.SqlMultiResult;
import com.mysql.cj.xdevapi.SqlResult;
import com.mysql.cj.xdevapi.UpdateResult;
import io.r2dbc.mysqlx.update.SingleValueRow;
import io.r2dbc.mysqlx.update.SingleValueRowMetadata;
import io.r2dbc.spi.R2dbcType;
import io.r2dbc.spi.Result;
import io.r2dbc.spi.Row;
import io.r2dbc.spi.RowMetadata;
import org.reactivestreams.Publisher;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.util.annotation.Nullable;

import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.Predicate;

/**
 * MySQL X R2DBC Result
 *
 * @author linux_china
 */
public class MysqlxResult implements Result {
    private final String sql;
    private final SqlResult sqlResult;
    @Nullable
    private final String autoGeneratedColumn;

    public MysqlxResult(String sql, SqlResult sqlResult, @Nullable String autoGeneratedColumn) {
        this.sql = sql;
        this.sqlResult = sqlResult;
        this.autoGeneratedColumn = autoGeneratedColumn;
    }

    @Override
    public Publisher<Long> getRowsUpdated() {
        return Mono.just(sqlResult.getAffectedItemsCount());
    }

    @Override
    public <T> Publisher<T> map(BiFunction<Row, RowMetadata, ? extends T> mappingFunction) {
        // select
        if (sqlResult instanceof SqlMultiResult) {
            return Flux.fromIterable(sqlResult).map(row -> {
                MysqlxRowMetadata rowMetadata = new MysqlxRowMetadata((SqlMultiResult) sqlResult);
                return mappingFunction.apply(new MysqlxRow(row, rowMetadata), rowMetadata);
            });
        } else if (sqlResult instanceof UpdateResult) { //insert, update, delete
            if (autoGeneratedColumn != null) {
                Long autoIncrementValue = sqlResult.getAutoIncrementValue();
                final SingleValueRowMetadata rowMetadata = new SingleValueRowMetadata(autoGeneratedColumn, Long.class, R2dbcType.BIGINT);
                final SingleValueRow<Long> singleValueRow = new SingleValueRow<>(autoGeneratedColumn, autoIncrementValue, rowMetadata);
                return Mono.just(mappingFunction.apply(singleValueRow, rowMetadata));
            } else {
                return Mono.empty();
            }
        }
        return Flux.empty();
    }

    @Override
    public Result filter(Predicate<Segment> filter) {
        return this;
    }

    @Override
    public <T> Publisher<T> flatMap(Function<Segment, ? extends Publisher<? extends T>> mappingFunction) {
        // select
        if (sqlResult instanceof SqlMultiResult) {
            return Flux.fromIterable(sqlResult).flatMap(row -> {
                MysqlxRowMetadata rowMetadata = new MysqlxRowMetadata((SqlMultiResult) sqlResult);
                return mappingFunction.apply((RowSegment) () -> new MysqlxRow(row, rowMetadata));
            });
        } else if (sqlResult instanceof UpdateResult) { //insert, update, delete
            if (autoGeneratedColumn != null) {
                Long autoIncrementValue = sqlResult.getAutoIncrementValue();
                return (Publisher<T>) mappingFunction.apply((UpdateCount) () -> autoIncrementValue);
            } else {
                return Mono.empty();
            }
        }
        return Flux.empty();
    }
}
